web/django_app/farma/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from medicamentos import views as mviews
from organizaciones import views as oviews
from pedidos import views as pviews
from usuarios import views as uviews

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^$', views.inicio, name="inicio"),
    url(r'^con_celery', views.test_con_celery, name="test_con_celery"),
    url(r'^sin_celery', views.test_sin_celery, name="test_sin_celery"),

    # =============================================================================================== #
    #                                       USUARIOS
    # =============================================================================================== #
    url(r'^login', uviews.login_user, name="login"),
    url(r'^logout', uviews.logout_user, name="logout"),
    url(r'^perfil/addUsuario/$', uviews.usuario_add, name="usuario_add"),

    # =============================================================================================== #
    #                                       MEDICAMENTOS
    # =============================================================================================== #
    
    # ***************************************** Monodroga *******************************************
    url(r'^monodrogas/$', mviews.monodrogas, name="monodrogas"),
    url(r'^monodrogas/add/$', mviews.monodroga_add, name="monodroga_add"),
    url(r'^monodrogas/update/(?P<id_monodroga>\d+)/$', mviews.monodroga_update, name="monodroga_update"),
    url(r'^monodrogas/tryDelete/(?P<id_monodroga>\d+)/$', mviews.monodroga_try_delete, name="monodroga_try_delete"),
    url(r'^monodrogas/delete/(?P<id_monodroga>\d+)/$', mviews.monodroga_delete, name="monodroga_delete"),

    # ************************************** Nombre Fantasia ****************************************
    url(r'^nombresFantasia/$', mviews.nombresFantasia, name="nombresFantasia"),
    url(r'^nombresFantasia/add/$', mviews.nombresFantasia_add, name="nombreFantasia_add"),
    url(r'^nombresFantasia/update/(?P<id_nombreFantasia>\d+)/$', mviews.nombresFantasia_update, name="nombreFantasia_update"),
    url(r'^nombresFantasia/tryDelete/(?P<id_nombreFantasia>\d+)/$', mviews.nombresFantasia_try_delete, name="nombreFantasia_try_delete"),
    url(r'^nombresFantasia/delete/(?P<id_nombreFantasia>\d+)/$', mviews.nombresFantasia_delete, name="nombreFantasia_delete"),

    # *************************************** Presentacion ******************************************
    url(r'^presentaciones/$', mviews.presentaciones, name="presentaciones"),
    url(r'^presentaciones/add/$', mviews.presentacion_add, name="presentacion_add"),
    url(r'^presentaciones/update/(?P<id_presentacion>\d+)/$', mviews.presentacion_update, name="presentacion_update"),
    url(r'^presentaciones/tryDelete/(?P<id_presentacion>\d+)/$', mviews.presentacion_try_delete, name="presentacion_try_delete"),
    url(r'^presentaciones/delete/(?P<id_presentacion>\d+)/$', mviews.presentacion_delete, name="presentacion_delete"),

    # **************************************** Medicamento ******************************************
    url(r'^medicamentos/$', mviews.medicamentos, name="medicamentos"),
    url(r'^medicamentos/add/$', mviews.medicamento_add, name="medicamento_add"),
    url(r'^medicamentos/updateStockMinimo/(?P<id_medicamento>\d+)/$', mviews.medicamento_updateStockMinimo, name="medicamento_update_stock_minimo"),
    url(r'^medicamentos/updatePrecioVenta/(?P<id_medicamento>\d+)/$', mviews.medicamento_updatePrecioVenta, name="medicamento_update_precio_venta"),
    url(r'^medicamentos/delete/(?P<id_medicamento>\d+)/$', mviews.medicamento_delete, name="medicamento_delete"),
    url(r'^medicamentos/tryDelete/(?P<id_medicamento>\d+)/$', mviews.medicamento_try_delete, name="medicamento_try_delete"),
    url(r'^medicamentos/verLotes/(?P<id_medicamento>\d+)/$', mviews.medicamento_verLotes, name="medicamento_verLotes"),
    url(r'^medicamentos/estadisticas/topPorCantidad/$', mviews.medicamentos_topPorCantidad, name="medicamentos_topPorCantidad"),
    url(r'^medicamentos/estadisticas/topPorCantidad/downloadExcel/$', mviews.medicamentos_topPorCantidadExcel, name="medicamentos_topPorCantidadExcel"),
    url(r'^medicamentos/estadisticas/topPorPedido/$', mviews.medicamentos_topPorPedido, name="medicamentos_topPorPedido"),
    url(r'^medicamentos/estadisticas/topPorPedido/downloadExcel/$', mviews.medicamentos_topPorPedidoExcel, name="medicamentos_topPorPedidoExcel"),
    url(r'^medicamentos/estadisticas/topOrganizacionesPorCantidad/$', mviews.medicamentos_topOrganizacionesPorCantidad, name="medicamentos_topOrganizacionesPorCantidad"),
    url(r'^medicamentos/estadisticas/topOrganizacionesPorCantidad/downloadExcel/$', mviews.medicamentos_topOrganizacionesPorCantidadExcel, name="medicamentos_topOrganizacionesPorCantidadExcel"),
    url(r'^medicamentos/estadisticas/topOrganizacionesPorPedidos/$', mviews.medicamentos_topOrganizacionesPorPedidos, name="medicamentos_topOrganizacionesPorPedidos"),
url(r'^medicamentos/estadisticas/topOrganizacionesPorPedido/downloadExcel/$', mviews.medicamentos_topOrganizacionesPorPedidoExcel, name="medicamentos_topOrganizacionesPorPedidoExcel"),

    # =============================================================================================== #
    #                                       ORGANIZACIONES
    # =============================================================================================== #

    # ***************************************** Farmacia *******************************************
    url(r'^farmacias/$', oviews.farmacias, name="farmacias"),
    url(r'^farmacias/add/$', oviews.farmacia_add, name="farmacia_add"),
    url(r'^farmacias/update/(?P<id_farmacia>\d+)/$', oviews.farmacia_update, name="farmacia_update"),
    url(r'^farmacias/tryDelete/(?P<id_farmacia>\d+)/$', oviews.farmacia_try_delete, name="farmacia_try_delete"),
    url(r'^farmacias/delete/(?P<id_farmacia>\d+)/$', oviews.farmacia_delete, name="farmacia_delete"),
    
    # ***************************************** Clinica *******************************************
    url(r'^clinicas/$',oviews.clinicas, name="clinicas"),
    url(r'^clinicas/add/$', oviews.clinica_add, name="clinica_add"),
    url(r'^clinicas/update/(?P<id_clinica>\d+)/$', oviews.clinica_update, name="clinica_update"),
    url(r'^clinicas/delete/(?P<id_clinica>\d+)/$', oviews.clinica_delete, name="clinica_delete"),

    # *************************************** Laboratorio *****************************************
    url(r'^laboratorios/$',oviews.laboratorios, name="laboratorios"),
    url(r'^laboratorios/add/$', oviews.laboratorio_add, name="laboratorio_add"),
    url(r'^laboratorios/update/(?P<id_laboratorio>\d+)/$', oviews.laboratorio_update, name="laboratorio_update"),
    url(r'^laboratorios/tryDelete/(?P<id_laboratorio>\d+)/$', oviews.laboratorio_try_delete, name="laboratorio_try_delete"),
    url(r'^laboratorios/delete/(?P<id_laboratorio>\d+)/$', oviews.laboratorio_delete, name="laboratorio_delete"),

    # *************************************** Obra Social *****************************************
    url(r'^obrasSociales/$', views.paginaEnConstruccion, name="paginaEnConstruccion"),

    # =============================================================================================== #
    #                                           PEDIDOS
    # =============================================================================================== #

    # ************************************** Pedido de Farmacia ***************************************
    url(r'^pedidosDeFarmacia/$', pviews.pedidosDeFarmacia, name="pedidosDeFarmacia"),
    url(r'^pedidosDeFarmacia/add/$', pviews.pedidoDeFarmacia_add, name="pedidoDeFarmacia_add"),  
    url(r'^pedidosDeFarmacia/add/registrar-pedido/$', pviews.pedidoDeFarmacia_registrar, name="pedidoDeFarmacia_registrar"),
    url(r'^pedidosDeFarmacia/ver/(?P<id_pedido>\d+)/$', pviews.pedidoDeFarmacia_ver, name="pedidoDeFarmacia_ver"),
    url(r'^pedidosDeFarmacia/verDetalles/(?P<id_pedido>\d+)/$', pviews.pedidoDeFarmacia_verDetalles, name="pedidoDeFarmacia_verDetalles"),
    url(r'^pedidosDeFarmacia/verRemitos/(?P<id_pedido>\d+)/$', pviews.pedidoDeFarmacia_verRemitos, name="pedidoDeFarmacia_verRemitos"),
    url(r'^pedidosDeFarmacia/add/detalles/$', pviews.detallesPedidoDeFarmacia, name="detallesPedidoDeFarmacia"),
    url(r'^pedidosDeFarmacia/add/detalles/add/$', pviews.detallePedidoDeFarmacia_add, name="detallePedidoDeFarmacia_add"),
    url(r'^pedidosDeFarmacia/add/detalles/update/(?P<id_detalle>\d+)/$', pviews.detallePedidoDeFarmacia_update, name="detallePedidoDeFarmacia_update"),
    url(r'^pedidosDeFarmacia/add/detalles/delete/(?P<id_detalle>\d+)/$', pviews.detallePedidoDeFarmacia_delete, name="detallePedidoDeFarmacia_delete"),
    url(r'^pedidosDeFarmacia/remitoDeFarmacia/(?P<id_remito>\d+)/$', pviews.remitoDeFarmacia.as_view(), name="remitoDeFarmacia"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadMedicamentos/$', pviews.pedidosDeFarmacia_topFarmaciasConMasMedicamentos, name="pedidosDeFarmacia_topFarmaciasConMasMedicamentos"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadMedicamentos/downloadExcel/$', pviews.pedidosDeFarmacia_topFarmaciasConMasMedicamentosExcel, name="pedidosDeFarmacia_topFarmaciasConMasMedicamentosExcel"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadPedidos/$', pviews.pedidosDeFarmacia_topFarmaciasConMasPedidos, name="pedidosDeFarmacia_topFarmaciasConMasPedidos"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadPedidos/downloadExcel/$', pviews.pedidosDeFarmacia_topFarmaciasConMasPedidosExcel, name="pedidosDeFarmacia_topFarmaciasConMasPedidosExcel"),


    # ************************************** Pedido de Clinica ***************************************

web/django_app/organizaciones/models.py
from django.db import models


class Organizacion(models.Model):
    FILTROS = ["razonSocial__icontains", "localidad__icontains"]
    razonSocial = models.CharField(max_length=50, unique=True)
    cuit = models.CharField(max_length=80, unique=True,
                            error_messages={'unique': "Ya existe una organizacion con este CUIT"})
    localidad = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, blank=True)
    telefono = models.CharField(max_length=80, blank=True)

    class Meta:
        abstract = True   


class Farmacia(Organizacion):
    nombreEncargado = models.CharField(max_length=80, blank=True)

    def __str__(self):
        return self.razonSocial


class Clinica(Organizacion):
    FILTROS = ["razonSocial__icontains", "localidad__icontains", "obraSocial__icontains"]
    obraSocial = models.CharField(max_length=200)

    def __str__(self):
        return self.razonSocial


class Laboratorio(Organizacion):

    def __str__(self):
        return self.razonSocial

web/django_app/pedidos/templates/pedidoDeClinica/detallesPedido.html
{% extends "base-presentacion-pedido.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Detalles del Pedido de Clinica{% endblock %}

{% block breadcrumb-items %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li><a href="{% url 'pedidosDeClinica' %}">Pedidos de Clínica</a></li>
    <li><a href="{% url 'pedidoDeClinica_add' %}">Alta</a></li>
    <li class="active">Detalles</li>
{% endblock %}

{% block header-title %} Detalles del Pedido de Clínica {% endblock%}

{% block url-volver %}{% url 'pedidoDeClinica_add' %}{% endblock %}

{% block botones-header-tabla %}
    <div class="btn-group btn-group-xs">
        <a id="btn-add-detalle" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span></a>
        <a id="btn-update-detalle" class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span></a>
        <a id="btn-delete-detalle" class="btn btn-danger"><span class="glyphicon glyphicon-minus"></span></a>
    </div>
{% endblock %}

{% block tipo-pedido %}Pedido de Clinica{% endblock %}

{% block pedido-organizacion %}{{ pedido.clinica.razonSocial }}{% endblock %}

{% block nro-pedido %} {{ pedido.nroPedido }} {% endblock %}

{% block table %}
    <table class="table table-condensed table-striped" >
        <thead>
            <tr align="center">
                <th>Medicamento</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% for detalle in detalles %}
                <tr class="clickeable" data-id="{{ detalle.renglon }}" data-medicamento="{{detalle.medicamento.id}}">
                    <td>{{ detalle.medicamento.descripcion }}</td>
                    <td>{{ detalle.cantidad }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block medicamento-stock-alta %}
    <p class="pull-right">
        <span class="medicamento-stock"></span>
    </p>
{% endblock %}

{% block medicamento-stock-modificacion %} 
    <p class="pull-right">
        <span class="medicamento-stock"></span>
    </p>
{% endblock %}

{% block url-remito %}"/pedidosDeClinica/remitoDeClinica/"+data['nroRemito']+"/"{% endblock %}

{% block panel-footer %}
    <div class="panel-footer">
        <div class="pull-right">
            <button id="btn-registrar" class="btn btn-primary" type="submit">Registrar</button>
        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block more-scripts %}
    <script>
        (function(){
            $('#modal-registrar-pedido').on('hidden.bs.modal', function(e){
                window.location = "{% url 'pedidosDeClinica' %}";
                e.stopPropagation();
            })

            /****************************** Botones Alta Detalle ***************************************/

            $("#btn-add-detalle").on("click", function(e){
                add_detalle_ajax("{% url 'detallePedidoDeClinica_add' %}");
                e.stopPropagation();
            });

            $("#btn-save-detalle").on("click", function(e){
                save_detalle_ajax("{% url 'detallePedidoDeClinica_add' %}");
                e.stopPropagation()
            });

            /****************************** Botones Modificacion Detalle ***************************************/
            var id;

            $("#btn-update-detalle").on("click", function(e){
                id = get_selected_row();
                if(id){
                    update_detalle_ajax("/pedidosDeClinica/add/detalles/update/" + id + "/");
                }
                e.stopPropagation();
            });

            $("#btn-save-update-detalle").on("click", function(e){
                if(id){
                    save_update_ajax("/pedidosDeClinica/add/detalles/update/" + id + "/");
                }
                e.stopPropagation();
            });

            /****************************** Boton Baja Detalle ***************************************/

            $("#btn-delete-detalle").on("click", function(e){
                var id = get_selected_row();
                if(id){
                    $("#modal-delete-detalle").modal('show');
                }
                e.stopPropagation();
            });

            $("#btn-confirmar-baja-detalle").on("click", function(e){
                var id = get_selected_row();
                if(id){
                    delete_detalle_ajax("/pedidosDeClinica/add/detalles/delete/" + id + "/");
                    $("#modal-delete-detalle").modal('hide');
                }
                e.stopPropagation();
            });

            /****************************** Boton Registrar Pedido ***************************************/

            $("#btn-registrar").on("click", function(e){
                registrar_pedido_ajax("{% url 'pedidoDeClinica_registrar' %}");
                e.stopPropagation();
            });
        })();

        (function(){
            var medicamentos = {
                {% for medicamentoStock in medicamentosStock %}
                    {{medicamentoStock.id}}: {{ medicamentoStock.stock}},
                {% endfor %}
            };

            $('#modal-add-detalle').on('show.bs.modal', function(){
                var $selectMedicamento = $(this).find('#id_medicamento');
                $selectMedicamento.on('change', load_stock.bind(this));
            });

            $('#modal-add-detalle').on('hidden.bs.modal', function(){
                $(this).find(".medicamento-stock").text("");
            });

            $('#modal-update-detalle').on('show.bs.modal', function(e){
                var idMedicamento = $('.clickeable.active').data('medicamento');
                $(this).find('.medicamento-stock').text("Disponible: " + medicamentos[idMedicamento])
            });

            $('#modal-update-detalle').on('hidden.bs.modal', function(){
                $(this).find(".medicamento-stock").text("");
            });

            function load_stock(e) {
                var idMedicamento = $(this).find('option:selected').val();
                if(idMedicamento){
                    $(this).find('.medicamento-stock').text('Disponible: ' + medicamentos[idMedicamento]);
                }else{
                    $(this).find('.medicamento-stock').text('-');
                }
            }

            $(document).on("keyup", function(e){
                if(e.keyCode == 112){
                    var url = "{% static 'documentacion/build/html/pedidosclinica.html' %}";
                    url += "#alta-pedido";
                    window.open(url);
                }
            });
        })();
    </script>
{% endblock %}

web/django_app/pedidos/templates/pedidoDeClinica/pedidoAdd.html
{% extends "base/base-add-update-2.html" %}
{% load staticfiles %}

{% block more-stylesheets %}
    <link rel="stylesheet" href="{%  static 'css/jquery-ui.custom.min.css'  %}">
    {{ form.media.css }}
    <link rel="stylesheet" href="{%  static 'css/selectize.css' %}">
    <link rel="stylesheet" href="{%  static 'css/selectize.bootstrap3.css' %}">
{% endblock %}

{% block title %}Alta Pedido De Clinica{% endblock %}

{% block breadcrumb-items %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li><a href="{% url 'pedidosDeClinica' %}">Pedidos de Clínica</a></li>
    <li class="active">Alta</li>
{% endblock %}

{% block url-volver %}{% url 'pedidosDeClinica' %}{% endblock %}

{% block header-title %} Alta Pedido de Clínica {% endblock %}

{% block title-header-form %}Agregar nuevo pedido de clínica{% endblock %}

{% block icon-header-form %}
    <span class="icon-file-text page-header-icon"></span>
{% endblock%}

{% block sub-header-form %}Complete los siguientes campos{% endblock %}

{% block no-msg-success %}
{% endblock %}

{% block more-scripts %}
<script src="{% static 'js/datepicker.js' %}"></script>
    {{ form.media.js }}
    <script type="text/javascript" src="{%  static 'js/selectize.js' %}"></script>
    <script>
        $('select').selectize({
            sortField: {
                field: 'text',
                direction: 'asc'
            },
            dropdownParent: 'body'
        });

        var $selectClinica = $('#id_clinica'),
            $selectObraSocial = $('#id_obraSocial');

        $selectClinica.on('change', setOptionsSelect);
        setOptionsSelect();

        function setOptionsSelect() {
            var id_clinica = $selectClinica.val()
            if(id_clinica) {
                $.ajax({
                    type: 'GET',
                    url: '/getObrasSociales/' + id_clinica + '/',
                    dataType: 'json',
                    success: function(data){
                        console.log(data)
                        var selectize =   $('select')[1].selectize;
                        selectize.clearOptions();
                        $.each(data, function(key, opt) {
                            selectize.addOption({value: opt['value'], text: opt['text']});
                        })
                    },
                    error: function(err){
                        alert("Fallo Ajax");
                    }
                });
            }
        }

        $(document).on("keyup", function(e){
            if(e.keyCode == 112){
                var url = "{% static 'documentacion/build/html/pedidosclinica.html' %}";
                url += "#alta-pedido";
                window.open(url);
            }
        });
    </script>
{% endblock %}

web/django_app/pedidos/templates/pedidoDeClinica/pedidoVer.html
{% extends "base-presentacion-pedido.html" %}

{% block title %}Ver Pedido De Clinica{% endblock %}

{% block more-crumbs %}
    <li><a href="{% url 'pedidosDeClinica' %}">Pedidos de clinica</a></li>
    <li class="active">Ver pedido de clinica</li>
{% endblock %}

{% block tipo-pedido %}Pedido de Clinica{% endblock %}

{% block nombre-organizacion %} {{ pedido.clinica.razonSocial }} {% endblock %}

{% block fecha-pedido %} {{ pedido.fecha }} {% endblock %}

{% block nro-pedido %} {{ pedido.nroPedido }} {% endblock %}

{% block panel-detalles %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <ul class="nav nav-pills">
              <li class="active"><a data-toggle="pill" href="#detalles-pedido">Detalles del pedido</a></li>
              <li><a data-toggle="pill" href="#remitos-pedido">Remitos del pedido</a></li>
            </ul>
        </div>
        <div class="panel-body">
            <div class="tab-content">
                <div id="detalles-pedido" class="tab-pane fade in active">
                    <table class="table table-condensed table-responsive" >
                        <thead>
                            <tr class="info" align="center">
                                <th>Medicamento</th>
                                <th>Cantidad</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for detalle in detalles %}
                                <tr>
                                    <td>{{ detalle.medicamento }}</td>
                                    <td>{{ detalle.cantidad }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div id="remitos-pedido" class="tab-pane fade">
                    <table class="table table-condensed table-responsive" >
                        <thead>
                            <tr class="info" align="center">
                                <th>Numero</th>
                                <th>Fecha</th>
                                <th>Descargar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for remito in remitos %}
                                <tr class="clickeable" data-id="{{ remito.id }}">
                                    <td>{{ remito.id }}</td>
                                    <td>{{ remito.fecha }}</td>
                                    <td>
                                        <a data-remito="{{ remito.id }}" class="btn btn-info btn-xs btn-generar" ><span class="glyphicon glyphicon-floppy-disk"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modals-abm %}
    <div class="modal fade" id="modal-generar-remito" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title">Generar remito</h3>
                </div>
                <div class="modal-body">
                    <p class="text-center text-success">¿Desea generar el remito?</p>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <a id="btn-pdf" target="_blank" class="btn btn-success">Si</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block more-scripts %}
    <script>
        $(".btn-generar").on("click", function(e){
            nroRemito = $(this).data("remito");
            $("#btn-pdf").attr("href","/pedidosDeClinica/remitoDeClinica/"+nroRemito+"/");
            $("#modal-generar-remito").modal('show');
            e.stopPropagation();
        });

        $("#btn-pdf").on("click", function(e){
            $("#modal-generar-remito").modal('hide');
        });
    </script>
{% endblock %}

{% block scripts-abm-detalles %}{% endblock %}

web/django_app/pedidos/templates/pedidoDeClinica/remitoDeClinica.html
{% extends "base-remito.html" %}

{% block header %} 
    <p class="logo"><img width="100%" src="images/logo-farma.jpg" /></p>
    <p>
        Tel (02965) 43-4159 <br>
        Lezama 479 <br/>
        Trelew, Chubut
    </p>
{% endblock%}

{% block cliente %}
    <p class="bottom-10">
        <strong>Clínica </strong> <span class="client">"{{remito.pedidoDeClinica.clinica}}"</span>
    </p>
    <p class="bottom-10">
        {%if remito.pedidoDeClinica.clinica.direccion %}
            {{ remito.pedidoDeClinica.clinica.direccion }}<br />
        {% endif %}
        {%if remito.pedidoDeClinica.clinica.localidad %}
            {{ remito.pedidoDeClinica.clinica.localidad }}
        {% endif %}        
        {%if remito.pedidoDeClinica.clinica.telefono %}
            {{ remito.pedidoDeClinica.clinica.telefono }}<br />
        {% endif %}
    </p>
{% endblock %}

{% block tipo-remito %}
    Remito de Clínica
{% endblock %}

{% block remito-cabecera %}
    <tr>
        <td class="item-name"><strong>Remito Nº {{ remito.pk }}</strong></td>
        <td><strong>{{ remito.fecha }}</strong></td>
    </tr>
{% endblock %}

{% block remito-detalles %}
    <thead>
        <tr>
            <th class="text-left">Medicamento</th>
            <th class="text-right">Cantidad</th>
            <th class="text-right">Lote</th>
        </tr>
    </thead>
    <tbody>
        {% for detalle in detallesRemito %}
        <tr>
            <td class="text-left">{{ detalle.detallePedidoDeClinica.medicamento }}</td>
            <td class="text-right">{{ detalle.cantidad }}</td>
            <td class="text-right">{{ detalle.lote }}</td>
        </tr>
        {% endfor %}
    </tbody>
{% endblock %}