web/django_app/farma/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from medicamentos import views as mviews
from organizaciones import views as oviews
from pedidos import views as pviews
from usuarios import views as uviews

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^$', views.inicio, name="inicio"),
    url(r'^con_celery', views.test_con_celery, name="test_con_celery"),
    url(r'^sin_celery', views.test_sin_celery, name="test_sin_celery"),

    # =============================================================================================== #
    #                                       USUARIOS
    # =============================================================================================== #
    url(r'^login', uviews.login_user, name="login"),
    url(r'^logout', uviews.logout_user, name="logout"),
    url(r'^perfil/addUsuario/$', uviews.usuario_add, name="usuario_add"),

    # =============================================================================================== #
    #                                       MEDICAMENTOS
    # =============================================================================================== #
    
    # ***************************************** Monodroga *******************************************
    url(r'^monodrogas/$', mviews.monodrogas, name="monodrogas"),
    url(r'^monodrogas/add/$', mviews.monodroga_add, name="monodroga_add"),
    url(r'^monodrogas/update/(?P<id_monodroga>\d+)/$', mviews.monodroga_update, name="monodroga_update"),
    url(r'^monodrogas/tryDelete/(?P<id_monodroga>\d+)/$', mviews.monodroga_try_delete, name="monodroga_try_delete"),
    url(r'^monodrogas/delete/(?P<id_monodroga>\d+)/$', mviews.monodroga_delete, name="monodroga_delete"),

    # ************************************** Nombre Fantasia ****************************************
    url(r'^nombresFantasia/$', mviews.nombresFantasia, name="nombresFantasia"),
    url(r'^nombresFantasia/add/$', mviews.nombresFantasia_add, name="nombreFantasia_add"),
    url(r'^nombresFantasia/update/(?P<id_nombreFantasia>\d+)/$', mviews.nombresFantasia_update, name="nombreFantasia_update"),
    url(r'^nombresFantasia/tryDelete/(?P<id_nombreFantasia>\d+)/$', mviews.nombresFantasia_try_delete, name="nombreFantasia_try_delete"),
    url(r'^nombresFantasia/delete/(?P<id_nombreFantasia>\d+)/$', mviews.nombresFantasia_delete, name="nombreFantasia_delete"),

    # *************************************** Presentacion ******************************************
    url(r'^presentaciones/$', mviews.presentaciones, name="presentaciones"),
    url(r'^presentaciones/add/$', mviews.presentacion_add, name="presentacion_add"),
    url(r'^presentaciones/update/(?P<id_presentacion>\d+)/$', mviews.presentacion_update, name="presentacion_update"),
    url(r'^presentaciones/tryDelete/(?P<id_presentacion>\d+)/$', mviews.presentacion_try_delete, name="presentacion_try_delete"),
    url(r'^presentaciones/delete/(?P<id_presentacion>\d+)/$', mviews.presentacion_delete, name="presentacion_delete"),

    # **************************************** Medicamento ******************************************
    url(r'^medicamentos/$', mviews.medicamentos, name="medicamentos"),
    url(r'^medicamentos/add/$', mviews.medicamento_add, name="medicamento_add"),
    url(r'^medicamentos/updateStockMinimo/(?P<id_medicamento>\d+)/$', mviews.medicamento_updateStockMinimo, name="medicamento_update_stock_minimo"),
    url(r'^medicamentos/updatePrecioVenta/(?P<id_medicamento>\d+)/$', mviews.medicamento_updatePrecioVenta, name="medicamento_update_precio_venta"),
    url(r'^medicamentos/delete/(?P<id_medicamento>\d+)/$', mviews.medicamento_delete, name="medicamento_delete"),
    url(r'^medicamentos/tryDelete/(?P<id_medicamento>\d+)/$', mviews.medicamento_try_delete, name="medicamento_try_delete"),
    url(r'^medicamentos/verLotes/(?P<id_medicamento>\d+)/$', mviews.medicamento_verLotes, name="medicamento_verLotes"),
    url(r'^medicamentos/estadisticas/topPorCantidad/$', mviews.medicamentos_topPorCantidad, name="medicamentos_topPorCantidad"),
    url(r'^medicamentos/estadisticas/topPorCantidad/downloadExcel/$', mviews.medicamentos_topPorCantidadExcel, name="medicamentos_topPorCantidadExcel"),
    url(r'^medicamentos/estadisticas/topPorPedido/$', mviews.medicamentos_topPorPedido, name="medicamentos_topPorPedido"),
    url(r'^medicamentos/estadisticas/topPorPedido/downloadExcel/$', mviews.medicamentos_topPorPedidoExcel, name="medicamentos_topPorPedidoExcel"),
    url(r'^medicamentos/estadisticas/topOrganizacionesPorCantidad/$', mviews.medicamentos_topOrganizacionesPorCantidad, name="medicamentos_topOrganizacionesPorCantidad"),
    url(r'^medicamentos/estadisticas/topOrganizacionesPorCantidad/downloadExcel/$', mviews.medicamentos_topOrganizacionesPorCantidadExcel, name="medicamentos_topOrganizacionesPorCantidadExcel"),
    url(r'^medicamentos/estadisticas/topOrganizacionesPorPedidos/$', mviews.medicamentos_topOrganizacionesPorPedidos, name="medicamentos_topOrganizacionesPorPedidos"),
url(r'^medicamentos/estadisticas/topOrganizacionesPorPedido/downloadExcel/$', mviews.medicamentos_topOrganizacionesPorPedidoExcel, name="medicamentos_topOrganizacionesPorPedidoExcel"),

    # =============================================================================================== #
    #                                       ORGANIZACIONES
    # =============================================================================================== #

    # ***************************************** Farmacia *******************************************
    url(r'^farmacias/$', oviews.farmacias, name="farmacias"),
    url(r'^farmacias/add/$', oviews.farmacia_add, name="farmacia_add"),
    url(r'^farmacias/update/(?P<id_farmacia>\d+)/$', oviews.farmacia_update, name="farmacia_update"),
    url(r'^farmacias/tryDelete/(?P<id_farmacia>\d+)/$', oviews.farmacia_try_delete, name="farmacia_try_delete"),
    url(r'^farmacias/delete/(?P<id_farmacia>\d+)/$', oviews.farmacia_delete, name="farmacia_delete"),
    
    # ***************************************** Clinica *******************************************
    url(r'^clinicas/$',oviews.clinicas, name="clinicas"),
    url(r'^clinicas/add/$', oviews.clinica_add, name="clinica_add"),
    url(r'^clinicas/update/(?P<id_clinica>\d+)/$', oviews.clinica_update, name="clinica_update"),
    url(r'^clinicas/delete/(?P<id_clinica>\d+)/$', oviews.clinica_delete, name="clinica_delete"),

    # *************************************** Laboratorio *****************************************
    url(r'^laboratorios/$',oviews.laboratorios, name="laboratorios"),
    url(r'^laboratorios/add/$', oviews.laboratorio_add, name="laboratorio_add"),
    url(r'^laboratorios/update/(?P<id_laboratorio>\d+)/$', oviews.laboratorio_update, name="laboratorio_update"),
    url(r'^laboratorios/tryDelete/(?P<id_laboratorio>\d+)/$', oviews.laboratorio_try_delete, name="laboratorio_try_delete"),
    url(r'^laboratorios/delete/(?P<id_laboratorio>\d+)/$', oviews.laboratorio_delete, name="laboratorio_delete"),

    # *************************************** Obra Social *****************************************
    url(r'^obrasSociales/$', views.paginaEnConstruccion, name="paginaEnConstruccion"),

    # =============================================================================================== #
    #                                           PEDIDOS
    # =============================================================================================== #

    # ************************************** Pedido de Farmacia ***************************************
    url(r'^pedidosDeFarmacia/$', pviews.pedidosDeFarmacia, name="pedidosDeFarmacia"),
    url(r'^pedidosDeFarmacia/add/$', pviews.pedidoDeFarmacia_add, name="pedidoDeFarmacia_add"),  
    url(r'^pedidosDeFarmacia/add/registrar-pedido/$', pviews.pedidoDeFarmacia_registrar, name="pedidoDeFarmacia_registrar"),
    url(r'^pedidosDeFarmacia/ver/(?P<id_pedido>\d+)/$', pviews.pedidoDeFarmacia_ver, name="pedidoDeFarmacia_ver"),
    url(r'^pedidosDeFarmacia/verDetalles/(?P<id_pedido>\d+)/$', pviews.pedidoDeFarmacia_verDetalles, name="pedidoDeFarmacia_verDetalles"),
    url(r'^pedidosDeFarmacia/verRemitos/(?P<id_pedido>\d+)/$', pviews.pedidoDeFarmacia_verRemitos, name="pedidoDeFarmacia_verRemitos"),
    url(r'^pedidosDeFarmacia/add/detalles/$', pviews.detallesPedidoDeFarmacia, name="detallesPedidoDeFarmacia"),
    url(r'^pedidosDeFarmacia/add/detalles/add/$', pviews.detallePedidoDeFarmacia_add, name="detallePedidoDeFarmacia_add"),
    url(r'^pedidosDeFarmacia/add/detalles/update/(?P<id_detalle>\d+)/$', pviews.detallePedidoDeFarmacia_update, name="detallePedidoDeFarmacia_update"),
    url(r'^pedidosDeFarmacia/add/detalles/delete/(?P<id_detalle>\d+)/$', pviews.detallePedidoDeFarmacia_delete, name="detallePedidoDeFarmacia_delete"),
    url(r'^pedidosDeFarmacia/remitoDeFarmacia/(?P<id_remito>\d+)/$', pviews.remitoDeFarmacia.as_view(), name="remitoDeFarmacia"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadMedicamentos/$', pviews.pedidosDeFarmacia_topFarmaciasConMasMedicamentos, name="pedidosDeFarmacia_topFarmaciasConMasMedicamentos"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadMedicamentos/downloadExcel/$', pviews.pedidosDeFarmacia_topFarmaciasConMasMedicamentosExcel, name="pedidosDeFarmacia_topFarmaciasConMasMedicamentosExcel"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadPedidos/$', pviews.pedidosDeFarmacia_topFarmaciasConMasPedidos, name="pedidosDeFarmacia_topFarmaciasConMasPedidos"),
    url(r'^pedidosDeFarmacia/estadisticas/topPorCantidadPedidos/downloadExcel/$', pviews.pedidosDeFarmacia_topFarmaciasConMasPedidosExcel, name="pedidosDeFarmacia_topFarmaciasConMasPedidosExcel"),


    # ************************************** Pedido de Clinica ***************************************

web/django_app/medicamentos/models.py
# - encode: utf-8 -
from django.db import models
from organizaciones.models import Laboratorio
from django.core.validators import MaxValueValidator, MinValueValidator
from pedidos import config as pconfig
from . import config
import datetime


class Medicamento(models.Model):
    FILTROS = ["nombreFantasia__nombreF__icontains", 'laboratorio__razonSocial__icontains']
    formulas = models.ManyToManyField('Monodroga',  through='Dosis')
    nombreFantasia = models.ForeignKey('NombreFantasia')
    presentacion = models.ForeignKey('Presentacion')
    codigoBarras = models.CharField("Codigo de barras", max_length=17, unique=True, error_messages={'unique': "Este codigo de barras ya esta cargado"})
    laboratorio = models.ForeignKey(Laboratorio, related_name="medicamentos")
    stockMinimo = models.PositiveIntegerField("Stock minimo de reposicion", validators=[MinValueValidator(1),
                                                                            MaxValueValidator(config.MAXIMO_STOCK_MINIMO)])
    precioDeVenta = models.DecimalField("Precio de venta", max_digits=12, decimal_places=2)

    def __str__(self):
        return "%s %s" % (self.nombreFantasia, self.presentacion)

    def get_stock(self):
        if self.id:
            stockTotal = 0
            lotes = self.get_lotes_activos()
            for lote in lotes:
                stockTotal += lote.stock
            return stockTotal

    def get_lotes_con_stock(self):
        lotes = self.get_lotes_activos()
        return lotes.filter(stock__gt=0)
        
    def get_lotes_activos(self):
        if self.id:
            lim = datetime.date.today() + datetime.timedelta(weeks=pconfig.SEMANAS_LIMITE_VENCIDOS)
            return Lote.objects.filter(medicamento=self, fechaVencimiento__gte=lim)
        return None


class Presentacion(models.Model):
    FILTROS = ["descripcion__icontains"]
    descripcion = models.CharField(max_length=45)
    cantidad = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), 
                                                      MaxValueValidator(config.MAXIMA_CANTIDAD_PRESENTACION)])
    unidadMedida = models.CharField("Unidad de medida", max_length=45)

    def __str__(self):
        return "%s - %s %s" % (self.descripcion, self.cantidad, self.unidadMedida)


class Formula(models.Model):
    monodroga = models.ForeignKey('Monodroga')
    dosis = models.ForeignKey('Dosis')


class Monodroga(models.Model):
    FILTROS = ["nombre__icontains"]
    nombre = models.CharField(max_length=75, unique=True, error_messages={'unique': "Esta monodroga ya esta cargada"})

    def __str__(self):
        return "%s" % self.nombre


class Dosis(models.Model):
    UNIDADES = (
        (1, "ml"),
        (2, "mg")
    )
    medicamento = models.ForeignKey(Medicamento)
    monodroga = models.ForeignKey(Monodroga)
    unidad = models.PositiveIntegerField(choices=UNIDADES)
    cantidad = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1), 
                                                     MaxValueValidator(config.MAXIMA_CANTIDAD_DOSIS)])

    def __str__(self):
        return "%s - %s" % (self.cantidad, self.get_unidad_display())


class NombreFantasia(models.Model):
    FILTROS = ["nombreF__icontains"]
    nombreF = models.CharField(max_length=75,  unique=True,error_messages={'unique': "Este nombre de fantasia ya esta cargado"})

    def __str__(self):
        return "%s" % self.nombreF


class Lote(models.Model):
    FILTROS = ["numero__icontains"]
    numero = models.PositiveIntegerField(unique=True, error_messages={'unique': "Este numero de lote ya esta cargado"})
    fechaVencimiento= models.DateField()
    stock = models.PositiveIntegerField()
    precio = models.FloatField()
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % self.numero

    def to_json(self):
        if self.numero:
            return {
                'nroLote': self.numero,
                'fechaVencimiento': self.fechaVencimiento.strftime("%d/%m/%y"),
                'stock': self.stock
            }

web/django_app/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from . import forms
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import permission_required


def get_permiso(tipoCargo):
    if tipoCargo == 'Encargado General':
        return Permission.objects.get(codename="encargado_general")

    if tipoCargo == 'Encargado Medicamentos Vencidos':
        return Permission.objects.get(codename="encargado_medicamentos_vencidos")

    if tipoCargo == 'Encargado de Stock':
        return Permission.objects.get(codename="encargado_stock")

    if tipoCargo == 'Encargado de Pedido':
        return Permission.objects.get(codename="encargado_pedido")

    if tipoCargo == 'Empleado de Despacho de Pedido':
        return Permission.objects.get(codename="empleado_despacho_pedido")


@csrf_protect
@permission_required('usuarios.encargado_general', login_url='login')
@login_required(login_url='login')
def usuario_add(request):
    if request.method == 'POST':
        form = forms.UsuarioAddForm(request.POST)
        if form.is_valid():
            usuario = form.save(commit="False")
            usuario.user_permissions.add(get_permiso(usuario.cargo))
            usuario.set_password(form.cleaned_data['password'])
            usuario.save()
            return redirect('/')
    else:
        form = forms.UsuarioAddForm()
    return render(request, 'usuarioAdd.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        form = forms.UsuarioLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('inicio')
        else:
            return render(request, "login.html", {'form':form})
    else: 
        form = forms.UsuarioLoginForm()
    return render(request, "login.html", {'form':form})


@login_required(login_url='login')
def logout_user(request):
    logout(request)
    return redirect('login')

web/django_app/medicamentos/templates/django_bootstrap_dynamic_formsets/dynamic_formsets_js.html
<script type="text/javascript">
    $(document).ready(function () {

        // Checks if input is empty or, in case of a checkbox, unchecked
        var checkEmpty = function ($inputToCheck) {
            var isEmpty = false;
            if ($inputToCheck.attr('type') === 'checkbox') {
                isEmpty = !$inputToCheck.prop('checked');
            } else {
                $inputToCheck.filter(function () {
                    isEmpty = !this.value;
                    return false;
                });
            }
            return isEmpty;
        };

        //Checks if all inputs in this container are empty/unchecked
        var allEmpty = function ($toCheck) {
            var isEmpty = true;
            $toCheck.find('input').each(function () {
                if (!checkEmpty($(this))) {
                    isEmpty = false;
                    return false;
                }
            });
            return isEmpty;
        };


        //Writes the correct current order in the order form fields
        var correctOrder = function () {
            var localSortItemCounter = 1;
            $("[id$=ORDER]").each(function () {
                $(this).attr('value', localSortItemCounter);
                localSortItemCounter++;
            });
        };

        //Hide "Order" and "Delete" field/checkbox
        $("[id$=ORDER]").parents(".form-group").hide();
        $("[id$=DELETE]").parents(".form-group").hide();

        //Holds an empty form
        var $emptyForm = $('#empty-form').remove().children().unwrap().removeClass('well');

        var $sortItem = $('.sort-item');

        //Disable Up button on first and Down button on last form
        var setUpDownButtons = function () {
            $sortItem = $('.sort-item');
            $sortItem.find(".up-form, .down-form").each(function () {
                $(this).prop("disabled", false);
            });
            $sortItem.first().find(".up-form").prop("disabled", true);
            $sortItem.last().find(".down-form").prop("disabled", true);
        };


        //Hide forms that are marked for deletion
        $sortItem.find('[id$=DELETE]').each(function () {
            if ($(this).prop('checked')) {
                $(this).parents(".sort-item").hide();
            }
        });


        //Counts the number of forms
        var sortItemCounter = 0;
        $sortItem.each(function () {
            sortItemCounter++;
        });
        //$('body').prepend('<p>Count: ' + sortItemCounter + '</p>');

        //Mark initial forms as such
        var numInitialForms = $('#id_{{formset.prefix}}-INITIAL_FORMS').val();
        var i = 0;
        $sortItem.each(function () {
            if (i < numInitialForms) {
                $(this).addClass("initial-form");
                i++;
            } else {
                return false;
            }
        });

        var numTotalForms = $('#id_{{formset.prefix}}-TOTAL_FORMS').val();
        //Fix order (important if page reloads after validation failed)
        for (i = 1; i < numTotalForms; i++) {
            $sortItem.find('[id$=ORDER][value=' + (i + 1) + ']').parents(".sort-item").insertAfter($sortItem.find('[id$=ORDER][value=' + i + ']').parents(".sort-item"));
        }


        //Set up sortable jQuery UI interaction
        {% if can_order %}

            var $sortable = $('#sortable');

            $sortable.sortable({
                items: ".sort-item",
                axis: "y",
                scrollSensitivity: 100,
                scrollSpeed: 5,
                tolerance: "intersect",
                handle: ".sort-handle",
                cancel: "input,textarea,select,option"
            });
            $sortable.on("sortupdate", function (event, ui) {
                setUpDownButtons();
            });
            setUpDownButtons();

            $(document).on('click', '.up-form', function () {
                var $parentSortItem = $(this).parents(".sort-item");
                $parentSortItem.insertBefore($parentSortItem.prev());
                setUpDownButtons();
            });

            $(document).on('click', '.down-form', function () {
                var $parentSortItem = $(this).parents(".sort-item");
                $parentSortItem.insertAfter($parentSortItem.next());
                setUpDownButtons();
            });


        {% endif %}

        //código propio
        
        function control_min_forms() {
            var $inputTotalForms = $('#id_form-TOTAL_FORMS'),
                btnDeleteFormDisabled = false;

                return function() {
                    if($inputTotalForms.attr('value') < 2 && !btnDeleteFormDisabled) {
                        $('.sort-item:eq(0)').find('.delete-form').prop('disabled', true).addClass('disabled');
                        btnDeleteFormDisabled = true;
                    }else {
                        if(btnDeleteFormDisabled) {
                            $('.sort-item:eq(0)').find('.delete-form').prop('disabled', false).removeClass('disabled');
                            btnDeleteFormDisabled = false;
                        }
                    }
                };
        };

        var start_control_min_forms = control_min_forms();
        start_control_min_forms();

        // Remove form
        $(document).on('click', '.delete-form', function () { 
            var $parentSortItem = $(this).parents(".sort-item");   
            if ($parentSortItem.hasClass('initial-form')) {
                $parentSortItem.effect('drop');
                $parentSortItem.find('[id$=DELETE]').prop('checked', true);
            } else {                    
                $parentSortItem.effect('drop', function () {
                    $(this).remove();
                    sortItemCounter--;
                    $('#id_{{formset.prefix}}-TOTAL_FORMS').attr('value', sortItemCounter);
                    start_control_min_forms(); 
                });
            }
        });

        // Add form
        $(document).on('click', '.add-form', function () {  
            var formCopy = $emptyForm.clone();
            var formCopyString = formCopy.html().replace(/__prefix__/g, "" + sortItemCounter);
            formCopy.html(formCopyString);
            sortItemCounter++;
            $(this).parents(".sort-item").after(formCopy);
            $('#id_{{formset.prefix}}-TOTAL_FORMS').attr('value', sortItemCounter);
            window.bindSelectables('body');
            start_control_min_forms();
        });

        //Submit formset
        $('#form-submit').click(function (e) {
            e.preventDefault();
            $('.sort-item').each(function () {
                if (allEmpty($(this))) {
                    $(this).remove();
                }
            });
            {% if can_order %}
                correctOrder();
            {% endif %}
            $(this).parents("form").submit();
        });

    });
</script>